source 'https://rubygems.org'


gem 'rails', '> 4'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem "rspec-rails"
end
