source 'https://rubygems.org'

gem 'rails', '~> 5.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.8'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'

# START:rspec-rails-gem
group :development, :test do
  gem 'rspec-rails', '~> 3.4'
  gem 'poltergeist'
end
# END:rspec-rails-gem

group :development do
  gem 'listen', '~> 3.0.5'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
