# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

# START: rm.2.3.setup
Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Todo'
  app.info_plist['NSAppTransportSecurity'] = {
    'NSExceptionDomains' => {
      'localhost' => {
        'NSIncludesSubdomains' => true,
        'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true,
      }
    }
  }
end
# END: rm.2.3.setup
