source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

#START:dev_and_test_gems
group :development, :test do
  gem "rspec-rails", "2.0.0"
  gem "cucumber-rails", "0.3.2"
  gem "webrat", "0.7.2"
  #START_HIGHLIGHT
  gem "database_cleaner", "0.5.2"
  gem "selenium-client", "1.2.18"
  #END_HIGHLIGHT
end
#END:dev_and_test_gems

