# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Todo'

  app.files << Dir.glob("../common/app/**/*.rb")

  app.development do
    app.files << Dir.glob(File.join(app.project_dir,
                                    'configuration/development/**/*.rb'))
  end

  app.info_plist['NSAppTransportSecurity'] = {
    'NSExceptionDomains' => {
      'localhost' => {
        'NSIncludesSubdomains' => true,
        'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true,
      }
    }
  }
end
