# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::configure("2") do |config|
  config.vm.box       = 'pairing-server'
  config.vm.box_url   = 'http://files.vagrantup.com/precise32.box'

  config.vm.network :forwarded_port, host: 3000, guest: 3000

  config.vm.provision :puppet do |puppet| 
    puppet.manifests_path = "puppet/manifests" 
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end
end
