source 'https://rubygems.org'

# START:install-webpacker
gem 'rails', '~> 5.1'
# START_HIGHLIGHT
gem 'webpacker'
# END_HIGHLIGHT
# END:install-webpacker
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.8'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
# START:install-devise
gem 'jbuilder', '~> 2.5'
# START_HIGHLIGHT
gem 'devise'
# END_HIGHLIGHT
# END:install-devise
gem 'foreman'
# END:install-foreman

# START:rspec-rails-gem
group :development, :test do
  gem 'rspec-rails', '~> 3.4'
  gem 'poltergeist'
end
# END:rspec-rails-gem

group :development do
  gem 'listen', '~> 3.0.5'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

