# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# START: new_gems
gem 'rspec',     '3.6.0'
gem 'coderay',   '1.1.1'
gem 'rack-test', '0.7.0'
gem 'sinatra',   '2.0.0'
# START: add_sequel
gem 'sequel',    '4.48.0'
gem 'sqlite3',   '1.3.13'
# END: add_sequel
# END: new_gems

gem 'pry', '0.10.4'