Vagrant::Config.run do |config|
  config.vm.define :app do |app_config|
    app_config.vm.customize ["modifyvm", :id, 
      "--name", "app", "--memory", "512"]
    app_config.vm.box = "lucid64_with_ruby193"
    app_config.vm.host_name = "app"
    app_config.vm.forward_port 22, 2222, :auto => true
    app_config.vm.forward_port 80, 4567
    app_config.vm.network :hostonly, "33.33.13.37"
    app_config.vm.share_folder "puppet", "/etc/puppet", "../massiveapp_ops"
  end
  config.vm.define :nagios do |nagios_config|
    nagios_config.vm.customize ["modifyvm", :id, 
      "--name", "nagios", "--memory", "512"]    
    nagios_config.vm.box = "lucid64_with_ruby193"
    nagios_config.vm.host_name = "nagios"
    nagios_config.vm.forward_port 22, 2222, :auto => true
    nagios_config.vm.forward_port 80, 4568
    nagios_config.vm.network :hostonly, "33.33.13.38"
    nagios_config.vm.share_folder "puppet", "/etc/puppet", "../massiveapp_ops"
  end
end

