source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

#START:gemfile
group :development, :test do
  gem "rspec-rails", "2.0.0"
  gem "webrat", "0.7.2"
end
#END:gemfile
