source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '> 4'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'rails_12factor', group: :production
gem 'puma'
gem 'devise'

group :development, :test do
  gem 'rspec-rails'
  gem 'poltergeist'
end
