source 'http://rubygems.org'

gem 'rails', '3.0.1'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'rspec-rails', '>= 2.1.0'
gem "mongrel", ">= 1.2.0.pre2"

gem 'sauce'
gem 'cucumber', '>=0.10.0'
gem 'database_cleaner', '>=0.5.0'
gem 'guard-cucumber', :git => 'https://github.com/jcnnghm/guard-cucumber.git' 
gem 'webrat'#, :git => 'http://github.com/notch8/webrat.git'
gem 'selenium-rc'
