require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  # START:JEWELER
  Jeweler::Tasks.new do |gem|
    gem.name = "autotest-stats"

    # Filled in the summary and description for our new plugin
    gem.summary = %Q{Collects and reports statistics about how you write tests}
    gem.description = %Q{An autotest plugin that monitors how you write tests 
      and reports interesting statistics as you work}
    
    #Adding ZenTest as a dependency
    gem.add_dependency "ZenTest", ">= 4.1.0"
    gem.files = FileList["[A-Z]*.*", "{lib,spec}/**/*"]
  #END:JEWELER
    gem.add_development_dependency "rspec", ">= 1.2.9"
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings

    gem.email = "benrady@gmail.com"
    gem.homepage = "http://github.com/benrady/autotest-stats"
    gem.authors = ["'Ben Rady'"]
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

Spec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :spec => :check_dependencies

task :default => :spec

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "autotest-stats #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
