source 'https://rubygems.org'

gem 'rails', '4.1.1'

gem 'sqlite3'

gem 'sass-rails', '~> 4.0.3'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

group :development, :test do
  gem "mocha", require: false
  gem 'rspec-rails', '~> 3.0'
end

group :test do
  gem "minitest-rails-capybara"
  gem 'm'
end
gem 'bcrypt-ruby', '~> 3.0.0'

group :test do
  gem 'capybara'
end

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end

gem 'spring',        group: :development
