source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', github: 'rails/rails'
gem 'arel',  github: 'rails/arel'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'rails_12factor', group: :production
gem 'puma'
gem 'devise', git: 'git@github.com:davetron5000/devise.git', branch: 'remove-hide-action'
gem 'bower-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'poltergeist'
end
