# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

# START: ios.setup.with.glob
Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Todo'
  # START_HIGHLIGHT
  app.files << Dir.glob("../common/app/**/*.rb")
  # END_HIGHLIGHT
  app.info_plist['NSAppTransportSecurity'] = {
    'NSExceptionDomains' => {
      'localhost' => {
        'NSIncludesSubdomains' => true,
        'NSTemporaryExceptionAllowsInsecureHTTPLoads' => true,
      }
    }
  }
end
# END: ios.setup.with.glob
