# Make a tasty lunch
sandwich: bread cheese
	echo "Grilling the sandwich"

# I guess sliced bread really is the greatest thing
bread:
	echo "Slicing the bread"

# Only the finest Emmentaler for our sandwich!
cheese:
	echo "Grating the cheese"
