source 'https://rubygems.org'

gem 'rails', '4.1.1'

gem 'sqlite3'

gem 'sass-rails', '~> 4.0.3'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'gravatar-ultimate'
gem 'twitter'

gem 'jbuilder', '~> 2.0'

group :development, :test do
  gem "mocha", require: false
  gem "rspec-rails", "~> 3.0.1"
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
end

group :test do
  gem "minitest-rails-capybara"
  gem 'm'
  gem 'minitest-reporters'
  gem 'vcr'
  gem 'webmock'
end
gem 'bcrypt-ruby', '~> 3.0.0'

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end

gem 'spring',        group: :development
