source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '> 4'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'rails_12factor', group: :production
gem 'puma'
gem 'devise'
gem 'bower-rails'
gem 'faker'

gem "angular-rails-templates"

group :development, :test do

  # rest of gems...
  
  gem 'rspec-rails'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'teaspoon-jasmine'
end
