require 'rake'
require 'rake/testtask'

desc 'Default: run unit tests.'
task :default => :test

desc 'Test the example unit tests.'
Rake::TestTask.new(:test) do |t|
  t.pattern = '**/*_test.rb'
  t.verbose = true
end