require 'rake/clean'
require 'cucumber'
require 'cucumber/rake/task'
require 'rubygems/package_task'

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/tc_*.rb']
end

spec = eval(File.read('todo.gemspec'))
Gem::PackageTask.new(spec) {}

CUKE_RESULTS = 'results.html'
CLEAN << CUKE_RESULTS
CLOBBER << 'tmp'
Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format html -o #{CUKE_RESULTS} --format progress -x"
  t.fork = false
end

task :default => :test
