source :rubygems

gem 'sinatra', '1.3.2'
gem 'service_manager', '0.6.4'

group :development do
  gem 'rspec', '2.11.0'
  gem 'cucumber', '1.2.1'
  gem 'capybara', '2.0.0.beta2'
  gem 'launchy', '2.1.0'
  gem 'activerecord', '3.2.7'
end

