/***
 * Excerpted from "CoffeeScript: Accelerated JavaScript Development, Second Edition",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material, 
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose. 
 * Visit http://www.pragmaticprogrammer.com/titles/tbcoffee2 for more book information.
***/
// Generated by CoffeeScript 1.6.3
(function() {
  var rl;

  rl = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.question("To whom am I speaking? ", function(audience) {
    return console.log("Hello, " + audience + "!");
  });

}).call(this);
