source "http://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"
#START:MONGO
gem 'mongo', "1.2.0"
gem 'bson_ext', "1.2.0"
#END:MONGO
#START:TWITTER
gem 'twitter', '1.1.1'
#END:TWITTER

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "rspec", "~> 2.3.0"
  gem "bundler", "~> 1.0.0"
  gem "jeweler", "~> 1.5.2"
  gem "rcov", ">= 0"
end
