# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2" 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'ubuntu/trusty64'  

    config.vm.hostname = "webdev" 

    config.vm.provider :virtualbox do |vb| 
      vb.customize ["modifyvm", :id, "--memory", "512", "--name", "webdev"]
    end 

    config.vm.synced_folder "site","/var/www/site" 

    config.vm.network :private_network, ip: "33.33.13.37" 

    config.vm.provision :puppet do |puppet| 
      puppet.options = ["--verbose --debug"]
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path    = "puppet/modules"
      puppet.manifest_file  = "site.pp"
    end 
end
