Vagrant::Config.run do |config|
  config.vm.define :app do |app_config|
    app_config.vm.customize ["modifyvm", :id, 
      "--name", "app", "--memory", "512"]
    app_config.vm.box = "lucid64_with_ruby193"
    app_config.vm.host_name = "app"
    app_config.vm.forward_port 22, 2222, :auto => true
    app_config.vm.forward_port 80, 4567
    app_config.vm.network :hostonly, "33.33.13.37"
    app_config.vm.share_folder "puppet", "/etc/puppet", "../massiveapp_ops"
  end
  config.vm.define :ganglia do |ganglia_config|
    ganglia_config.vm.customize ["modifyvm", :id, 
      "--name", "ganglia", "--memory", "512"]
    ganglia_config.vm.box = "lucid64_with_ruby193"
    ganglia_config.vm.host_name = "ganglia"
    ganglia_config.vm.forward_port 22, 2222, :auto => true
    ganglia_config.vm.forward_port 80, 4569
    ganglia_config.vm.network :hostonly, "33.33.13.38"
    ganglia_config.vm.share_folder "puppet", "/etc/puppet", "../massiveapp_ops"
  end
end

