/***
 * Excerpted from "Web Development Recipes",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material, 
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose. 
 * Visit http://www.pragmaticprogrammer.com/titles/wbdev2 for more book information.
***/
// Generated by CoffeeScript 1.8.0
(function() {
  $.ajax("/products.json", {
    type: "GET",
    dataType: "json",
    success: function(data, status, XHR) {
      var html, template;
      template = Handlebars.compile($("#product_template").html());
      html = template({
        products: data
      });
      return $('body').append(html);
    },
    error: function(XHR, status, errorThrown) {
      var html, template;
      template = Handlebars.compile($("#error_template").html());
      html = template({
        error: "Can't load data: " + errorThrown
      });
      return $('body').append(html);
    }
  });

}).call(this);
